# Generated by Django 5.2.12 on 2026-03-13 09:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CatName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StatusName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubCatName', models.CharField(max_length=100)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestTaskApp.transactioncategory')),
            ],
        ),
        migrations.AddField(
            model_name='transactioncategory',
            name='Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestTaskApp.transactiontype'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactionDate', models.DateField(default=datetime.date.today)),
                ('TransactionSumm', models.IntegerField()),
                ('Commentary', models.CharField(blank=True, max_length=1000)),
                ('Subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestTaskApp.subcategory')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestTaskApp.transactioncategory')),
                ('Status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestTaskApp.transactionstatus')),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestTaskApp.transactiontype')),
            ],
        ),
    ]
