# Generated by Django 5.2.12 on 2026-03-16 10:17

from django.db import migrations


def add_initial_data(apps, schema_editor):
    # Получаем модели через apps.get_model
    TransactionStatus = apps.get_model('TestTaskApp', 'TransactionStatus')
    TransactionType = apps.get_model('TestTaskApp', 'TransactionType')
    TransactionCategory = apps.get_model('TestTaskApp', 'TransactionCategory')
    Subcategory = apps.get_model('TestTaskApp', 'Subcategory')

    # Добавляем статусы
    status_list = ['Бизнес', 'Личное', 'Налог']
    statuses = {name: TransactionStatus.objects.create(StatusName=name) for name in status_list}

    # Добавляем типы транзакций
    type_list = ['Пополнение', 'Списание']
    types = {name: TransactionType.objects.create(TypeName=name) for name in type_list}

    # Добавляем категории
    category_data = [
        ('Инфраструктура', 'Пополнение'),
        ('Маркетинг', 'Списание'),
    ]
    categories = {}
    for cat_name, type_name in category_data:
        categories[cat_name] = TransactionCategory.objects.create(
            CatName=cat_name,
            Type=types[type_name]
        )

    # Добавляем подкатегории
    subcategory_data = [
        ('VPS', 'Инфраструктура'),
        ('Proxy', 'Инфраструктура'),
        ('Farpost', 'Маркетинг'),
        ('Avito', 'Маркетинг'),
    ]
    subcategories = {}
    for sub_name, cat_name in subcategory_data:
        subcategories[sub_name] = Subcategory.objects.create(
            SubCatName=sub_name,
            Category=categories[cat_name]
        )

def reverse_initial_data(apps, schema_editor):
    # Для отката миграции
    Subcategory = apps.get_model('TestTaskApp', 'Subcategory')
    TransactionCategory = apps.get_model('TestTaskApp', 'TransactionCategory')
    TransactionType = apps.get_model('TestTaskApp', 'TransactionType')
    TransactionStatus = apps.get_model('TestTaskApp', 'TransactionStatus')

    Subcategory.objects.all().delete()
    TransactionCategory.objects.all().delete()
    TransactionType.objects.all().delete()
    TransactionStatus.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('TestTaskApp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_initial_data, reverse_initial_data),
    ]
